feat!: prepare templates for 2.0
sern-handler/templates pull request #19
Opened 2022-12-15 17:51 UTC by jacoobes

2022-12-30 15:08 UTC, EvolutionX-10 requested changes
has this been tested, like the exact template (all js,ts,,js-esm) properly?

2022-12-30 15:08 UTC, EvolutionX-10 commented on templates/typescript/src/index.ts
> +	commands: 'src/commands',
shouldn't it be dist?

2022-12-30 15:09 UTC, jacoobes commented on templates/typescript/src/index.ts
> +	commands: 'src/commands',
yeah

2022-12-30 15:09 UTC, jacoobes commented on templates/typescript/src/index.ts
> +	commands: 'src/commands',
oops

2022-12-30 15:10 UTC, jacoobes commented
https://cdn.discordapp.com/attachments/941005497803374702/1058062009633099897/image.png

2022-12-30 15:10 UTC, jacoobes commented
one more thing to double check

2023-01-07 01:15 UTC, jacoobes commented
> has this been tested, like the exact template (all js,ts,,js-esm) properly?

Yes, should be all good

2023-01-08 13:13 UTC, EvolutionX-10 approved these changes

2023-01-08 13:14 UTC, merged

2023-01-09 06:25 UTC, jacoobes commented
Poggers